### ISSUE TITLE
Story : implement Kubernetes client to interact with Kubernetes cluster

### ISSUE THREAD

**Issue by adbusa67** [gopay-bootcamp/octavius#52]
#### Description 
There should be one Kubernetes client that can interact with the Kubernetes cluster according to the request from the executor. 

#### Sub-stories 
Kubernetes client should be able to
- [ ]   execute the job in Kubernetes cluster
- [ ]  send the job status from cluster to executor
- [ ]  get status while waiting for jobs and pods
- [ ]  create new Kubernetes client with the configurations in the executor

#### Present Behaviour 
No such behavior 

#### Expected Behaviour 
The Kubernetes client should be able to interact with the Kubernetes cluster.
